import type {
  AuditEvent,
  DashboardRow,
  DecisionRecord,
  OutputItem,
  ReviewIssue,
  SourceDefinition,
  ValidationState,
} from './types'

export const dashboardRows: DashboardRow[] = [
  {
    id: '1',
    intelModel: 'SEMI-0001',
    status: 'Draft',
    owner: 'Damian',
    lastUpdated: 'Today, 08:30',
  },
  {
    id: '2',
    intelModel: 'SEMI-0002',
    status: 'In progress',
    owner: 'Damian',
    lastUpdated: 'Yesterday, 15:20',
  },
  {
    id: '3',
    intelModel: 'SEMI-0003',
    status: 'Completed',
    owner: 'Damian',
    lastUpdated: 'Apr 24, 11:05',
  },
]

export const sourceDefinitions: SourceDefinition[] = [
  {
    id: '1',
    name: 'Fishbowl',
    type: 'Excel',
    location: 'Local file / Fishbowl export',
    scope: 'Global',
  },
  {
    id: '2',
    name: 'Mass Production',
    type: 'Excel',
    location: 'SharePoint / Production / Forecast',
    scope: 'Global',
  },
  {
    id: '3',
    name: 'Parts&BOM',
    type: 'Excel',
    location: 'SharePoint / Production / Parts',
    scope: 'Global',
  },
  {
    id: '4',
    name: 'BOX documentation',
    type: 'PDF / Folder',
    location: 'Local folder / BOX documentation',
    scope: 'Global',
  },
  {
    id: '5',
    name: 'Sharepoint documentation',
    type: 'PDF / SharePoint',
    location: 'SharePoint / Documentation',
    scope: 'Global',
  },
  {
    id: '6',
    name: 'PLM SQL connection',
    type: 'SQL',
    location: 'Configured connection',
    scope: 'Global',
  },
]

export const validationStatesBySource: Record<string, { state: ValidationState; message: string }> = {
  Fishbowl: { state: 'Valid', message: 'Source checked and ready.' },
  'Mass Production': { state: 'Warning', message: 'Imported with minor gaps to review.' },
  'Parts&BOM': { state: 'Valid', message: 'Structure looks correct.' },
  'BOX documentation': { state: 'Error', message: 'Missing required file mapping.' },
  'Sharepoint documentation': { state: 'Not checked', message: 'Validation has not been run yet.' },
  'PLM SQL connection': { state: 'Valid', message: 'Connection test passed.' },
}

export const reviewIssues: ReviewIssue[] = [
  {
    id: 'issue-001',
    title: 'Missing component in L1 BOM',
    area: 'BOM / L1',
    severity: 'High',
    status: 'Open',
    source: 'Parts&BOM',
    comparedWith: 'Fishbowl',
    decision: 'Required',
    owner: 'Damian',
    updated: 'Today, 09:12',
    description: 'Parts&BOM contains a component that is not present in the Fishbowl baseline for the selected L1 structure.',
    suggestedAction: 'Review the L1 structure and decide whether the component should be added to the output or rejected as source noise.',
  },
  {
    id: 'issue-002',
    title: 'Quantity mismatch on MATVAR row',
    area: 'BOM / MATVAR',
    severity: 'Medium',
    status: 'In review',
    source: 'Fishbowl',
    comparedWith: 'Parts&BOM',
    decision: 'None',
    owner: 'Damian',
    updated: 'Today, 08:44',
    description: 'The same material appears in both sources, but the quantity does not match the expected MATVAR setup.',
    suggestedAction: 'Check which source should drive the quantity before creating a decision record.',
  },
  {
    id: 'issue-003',
    title: 'Documentation link missing for BOX package',
    area: 'Documentation',
    severity: 'High',
    status: 'Open',
    source: 'BOX documentation',
    comparedWith: 'Sharepoint documentation',
    decision: 'Required',
    owner: 'Damian',
    updated: 'Yesterday, 16:20',
    description: 'BOX documentation has no matching SharePoint document reference for this package.',
    suggestedAction: 'Confirm whether the missing link blocks review output or should be recorded as a documentation exception.',
  },
  {
    id: 'issue-004',
    title: 'Costing source ready but not reviewed',
    area: 'Costing',
    severity: 'Low',
    status: 'Open',
    source: 'Mass Production',
    comparedWith: 'PLM SQL connection',
    decision: 'None',
    owner: 'Damian',
    updated: 'May 5, 13:05',
    description: 'Costing inputs are connected and available, but no review action has been taken yet.',
    suggestedAction: 'Review costing inputs after BOM issues are triaged.',
  },
  {
    id: 'issue-005',
    title: 'Parent-child structure confirmed',
    area: 'BOM / L2',
    severity: 'Low',
    status: 'Resolved',
    source: 'Parts&BOM',
    comparedWith: 'PLM SQL connection',
    decision: 'Accepted',
    owner: 'Damian',
    updated: 'May 2, 10:30',
    description: 'The parent-child structure was checked and marked as acceptable for this review pass.',
    suggestedAction: 'Keep the accepted decision linked to the final output history.',
  },
]

export const decisionRecords: DecisionRecord[] = [
  {
    issueId: 'issue-001',
    issueTitle: 'Missing component in L1 BOM',
    area: 'BOM / L1',
    status: 'Required',
    proposedDecision: 'Decide whether the missing L1 component should be included in the final output.',
    rationale: 'The difference affects the BOM structure and should not be resolved implicitly by the system.',
    outputImpact: 'Blocks output',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Today, 09:12',
    source: 'Parts&BOM',
    comparedWith: 'Fishbowl',
  },
  {
    issueId: 'issue-002',
    issueTitle: 'Quantity mismatch on MATVAR row',
    area: 'BOM / MATVAR',
    status: 'Drafted',
    proposedDecision: 'Use Parts&BOM quantity as the review baseline for this MATVAR row.',
    rationale: 'Parts&BOM is the intended source for this setup, but the final decision still needs confirmation.',
    outputImpact: 'Affects output',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Today, 08:44',
    source: 'Fishbowl',
    comparedWith: 'Parts&BOM',
  },
  {
    issueId: 'issue-003',
    issueTitle: 'Documentation link missing for BOX package',
    area: 'Documentation',
    status: 'Required',
    proposedDecision: 'Confirm whether documentation gap can be carried as an exception.',
    rationale: 'The issue belongs to documentation readiness and should be visible before output is generated.',
    outputImpact: 'Documentation only',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Yesterday, 16:20',
    source: 'BOX documentation',
    comparedWith: 'Sharepoint documentation',
  },
  {
    issueId: 'issue-004',
    issueTitle: 'Costing source ready but not reviewed',
    area: 'Costing',
    status: 'Deferred',
    proposedDecision: 'Defer costing review until BOM issue triage is complete.',
    rationale: 'Costing is available, but BOM structure decisions should be settled first.',
    outputImpact: 'No output impact yet',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'May 5, 13:05',
    source: 'Mass Production',
    comparedWith: 'PLM SQL connection',
  },
  {
    issueId: 'issue-005',
    issueTitle: 'Parent-child structure confirmed',
    area: 'BOM / L2',
    status: 'Accepted',
    proposedDecision: 'Keep the reviewed parent-child structure in the output baseline.',
    rationale: 'The structure was checked and accepted for this review pass.',
    outputImpact: 'Affects output',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'May 2, 10:30',
    source: 'Parts&BOM',
    comparedWith: 'PLM SQL connection',
  },
]

export const outputItems: OutputItem[] = [
  {
    id: 'output-l1-bom',
    title: 'L1 BOM update package',
    area: 'BOM / L1',
    linkedIssueId: 'issue-001',
    description: 'Prepared output candidate for the L1 BOM structure after the missing component issue is resolved.',
    sourceBasis: 'Parts&BOM vs Fishbowl',
    outputImpact: 'Blocks output',
    artifactRole: 'BOM package',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Today, 09:18',
  },
  {
    id: 'output-matvar-quantity',
    title: 'MATVAR quantity review output',
    area: 'BOM / MATVAR',
    linkedIssueId: 'issue-002',
    description: 'Output candidate for MATVAR quantity alignment, waiting for the decision to be accepted.',
    sourceBasis: 'Fishbowl vs Parts&BOM',
    outputImpact: 'Affects output',
    artifactRole: 'Quantity update',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Today, 08:50',
  },
  {
    id: 'output-documentation-exception',
    title: 'Documentation exception note',
    area: 'Documentation',
    linkedIssueId: 'issue-003',
    description: 'Documentation output note that can only be included after the missing link decision is settled.',
    sourceBasis: 'BOX documentation vs Sharepoint documentation',
    outputImpact: 'Documentation only',
    artifactRole: 'Exception note',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'Yesterday, 16:28',
  },
  {
    id: 'output-costing-hold',
    title: 'Costing readiness hold',
    area: 'Costing',
    linkedIssueId: 'issue-004',
    description: 'Costing output remains on hold until BOM decisions are clear enough to support final output.',
    sourceBasis: 'Mass Production vs PLM SQL connection',
    outputImpact: 'No output impact yet',
    artifactRole: 'Readiness note',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'May 5, 13:10',
  },
  {
    id: 'output-l2-structure',
    title: 'L2 structure baseline',
    area: 'BOM / L2',
    linkedIssueId: 'issue-005',
    description: 'Accepted parent-child structure that is ready to be represented in the final output baseline.',
    sourceBasis: 'Parts&BOM vs PLM SQL connection',
    outputImpact: 'Affects output',
    artifactRole: 'BOM baseline',
    auditState: 'Not persisted',
    owner: 'Damian',
    updated: 'May 2, 10:34',
  },
]

export const auditEvents: AuditEvent[] = [
  {
    id: 'audit-001',
    type: 'Issue',
    title: 'Issue marked for decision',
    actor: 'Damian',
    timestamp: 'Today, 09:15',
    relatedTo: 'Missing component in L1 BOM',
    state: 'Preview only',
    persistence: 'Source snapshot',
    summary: 'The L1 BOM issue was marked as requiring a decision.',
    detail: 'This preview event represents the future audit trail for moving an issue from review triage into the decision workflow.',
  },
  {
    id: 'audit-002',
    type: 'Decision',
    title: 'Decision drafted',
    actor: 'Damian',
    timestamp: 'Today, 09:20',
    relatedTo: 'Quantity mismatch on MATVAR row',
    state: 'Preview only',
    persistence: 'Source snapshot',
    summary: 'A draft decision was prepared for the MATVAR quantity mismatch.',
    detail: 'This will later become a persisted decision-history event with author, timestamp and before/after state.',
  },
  {
    id: 'audit-003',
    type: 'Decision',
    title: 'Decision accepted',
    actor: 'Damian',
    timestamp: 'May 2, 10:32',
    relatedTo: 'Parent-child structure confirmed',
    state: 'Preview only',
    persistence: 'Source snapshot',
    summary: 'The parent-child structure decision was accepted for output readiness.',
    detail: 'Accepted decisions should later explain why an output item is considered ready.',
  },
  {
    id: 'audit-004',
    type: 'Output',
    title: 'Output prepared',
    actor: 'Damian',
    timestamp: 'Today, 09:25',
    relatedTo: 'L2 structure baseline',
    state: 'Not persisted',
    persistence: 'Source snapshot',
    summary: 'An output candidate was prepared from an accepted decision.',
    detail: 'This preview keeps output as a separate artifact while signaling that no durable audit record exists yet.',
  },
]
